dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: gF2I2outZmVbHStnViXYzk4Q3J2vO2EtDt4Z52FcngY7MIBWGlYIALQxM593SjE/56u06mRyrByIFSCbPH6JnoqD3lBdZxGCSu96U9pDQJuZkBicHbXYfgd0/HUVxwzfSeAr8G1TOWsiQNyfuZPCVffNGo+Bv1IfcOYmzuAKaEY+r7wYxXReLnxhpSDU+hZ+6mki4z6FhTIcHAv3goWhNUM9mQTaF1tprbUniRa662YLafChCnkfZdeHmMvXuCOXe4eXj0dOjDV/gkMddEbiLy94x5AN/WzAw7iAlOiE4K76vwdeCfE6eZ0AaT14Cp4cgJaKaQWKWeeNwKyf1JTlHSR3PQJyc81Tsm8Wxa2Pjnk7kuwMzvdULsChgOOQq/dofQhuaXUCIJvSvl8q28V4ad3Rd9W0ZO2rodgKGWNxMEwNaZ45k4JGgx4W9vO5YsBVzko6aVgyoWNtF9wNZ74+hQCXZmnWBkDqXj0ifAeq1RKhtGmxym6Lxu5zWvT6tGaDOaO9qTKbtw0W+k5isDY/3eYua2TAbsWCeI3+wvbaR0zcgGXyFReLK4tMmTYnTcihG8MrNxlPaHPua8c/PiZgpC5JdkWNIrXWSceV8cs5+DXbgTiZWSxhnyXe7iORg/vFnwCwaY12O9AhM3Jbp5iv5rwQFP9cJvDHZYEb/JSJXnc=
